### ISSUE TITLE
Extending the approach to multi-label classification

### ISSUE THREAD

**Issue by RibinMathewChalumattu** [JiaQiSJTU/FaithEval-FFLM#1]
Hi,

Is it possible to extend the current fflm approach to multi-label faithful classification? Currently, I have 3 labels, namely _Faithful_, _Intrinsic Hallucination_ and _Extrinsic Hallucination_, to distinguish between different hallucination types.

**Comment by JiaQiSJTU** [comment]
Hi,

Thanks a lot for your interest in our work.

The most direct way I can come up with now is to transform the multi-label classification task into multiple binary classification tasks. Specifically, you can adapt fflm to distinguish the intrinsic hallucinations from the other generations and distinguish the extrinsic hallucinations from the others respectively. Then, you can take the intersection of the two to collect the faithful ones.
Of course, the weights of each component in fflm for both cases are not the same and should be searched with corresponding validation sets.

**Comment by RibinMathewChalumattu** [comment]
Hi,

Thank you for the suggestion. Instead of the intersection approach, could I use a multi-step classification approach, where I first classify the samples as either faithful or unfaithful and then a second classifier which assign the unfaithful samples from the previous step to either Intrinsic or Extrinsic? What could be the drawback of this approach compared to your suggestion?

**Comment by JiaQiSJTU** [comment]
This is also a feasible solution. In this paper, we didn't distinguish the intrinsic and extrinsic hallucinations. So, a major concern could be the success rate of the second classifier.
