### ISSUE TITLE
decapoda-research/llama-7b-hf model unavailable on Hugging Face Hub

### ISSUE THREAD

**Issue by SamarthGarg09** [JiaQiSJTU/FaithEval-FFLM#3]
Hi there,

I have been attempting to access the decapoda-research/llama-7b-hf model on the Hugging Face Model Hub but it appears unavailable. Whenever I try to access it, I receive an error message indicating that the model cannot be found. Can you please provide me with some guidance on alternative models that would be suitable for calculating FFLM scores? Also, I am wondering if the baffo32/decapoda-research-llama-7B-hf model would be an appropriate substitute.

Thank you.

**Comment by JiaQiSJTU** [comment]
Hi there,


I think "baffo32/decapoda-research-llama-7B-hf" is an appropriate substitute.


Regards,
Qi
















At 2024-03-09 12:33:08, "Samarth Garg" ***@***.***> wrote:

Hi there,

I have been attempting to access the decapoda-research/llama-7b-hf model on the Hugging Face Model Hub but it appears unavailable. Whenever I try to access it, I receive an error message indicating that the model cannot be found. Can you please provide me with some guidance on alternative models that would be suitable for calculating FFLM scores? Also, I am wondering if the baffo32/decapoda-research-llama-7B-hf model would be an appropriate substitute.

Thank you.

**Comment by SamarthGarg09** [comment]
I have one more question. What does a negative fflm score mean, and is closer to zero or -1 better? 

Thank you.

**Comment by JiaQiSJTU** [comment]
Overall, the higher the score, the better. It's hard to say if any output surpassing a specific threshold is sufficiently faithful. The score may hold more significance when making comparisons.
